.\"	$OpenBSD: mdoc.template,v 1.15 2014/03/31 00:09:54 dlg Exp $
.\"
.\" Copyright (c) 2018 Aaron Bieber <aaron@bolddaemon.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: June 13 2018 $
.Dt PLEDGE 1
.Os
.Sh NAME
.Nm pledge
.Nd test pledges for command
.Sh SYNOPSIS
.Nm program
.Fl p
.Op Ar pledges
.Ar command
.Sh DESCRIPTION
The
.Nm
utility runs specified commands with the specified set of pledges.
The options are as follows:
.Bl -tag -width Ds
.It Fl p Ar pledges
The set of pledges to be passed to command.
.El
.Sh SEE ALSO
.Xr pledge 2
.Sh AUTHORS
The
.Nm
utility was written by
.An Aaron Bieber Aq Mt aaron@bolddaemon.com .
.\" .Sh CAVEATS
.\" .Sh BUGS
